### ISSUE TITLE
Host app on fractalframework.xyz domain

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#122]
@dannydecent do you have access to fractalframework.xyz DNS?

Is that the domain we want to host at? It's quite long...

**Comment by adamgall** [comment]
How this should work:

- Have @moondog point NS records at a CloudFlare account
- Give Adam/Danny access to that CloudFlare account so that we can edit DNS entries

**Comment by dannydecent** [comment]
app.fractalframework.xyz

- update FAQ copy "voting allocation" to "Delegate"
- add github link to page 
- add app cta to top nav
