### ISSUE TITLE
When network changes, recognize if loaded DAO is no longer valid and respond appropriately

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#182]
Currently, if a DAO is loaded, and user changes their network, the UI kinda hangs because the loaded DAO is no longer valid (the address on the new network _likely_ is not a valid DAO on the new network).

The app should recognize this and probably kick the user back home, giving them an informational toast on what just happened.

**Comment by adamgall** [comment]
@Da-Colon i spent approx 10 mins last night looking at the code trying to figure out where to make this happen, and gave up because it wasn't intuitive. interested to see what path you take

**Comment by Da-Colon** [comment]
@adamgall I might have gotten it.
