### ISSUE TITLE
connect wallet modal and options

### ISSUE THREAD

**Issue by dannydecent** [fractal-framework/fractal-interface#194]

**Comment by dannydecent** [comment]
Current 
![image](https://user-images.githubusercontent.com/100443989/166974290-307e0deb-8cfe-400c-85cf-7663ad43dbcf.png)

Created pattern, to implement: (adding in coinbase real nice to have)
![image](https://user-images.githubusercontent.com/100443989/166974244-d54ae99c-b6eb-499f-b39d-f9829ecc22fa.png)

**Comment by adamgall** [comment]
what's the issue here @dannydecent ?
