### ISSUE TITLE
Form Validation -- Add helpful messages

### ISSUE THREAD

**Issue by sethhrbek** [fractal-framework/fractal-interface#195]
Update the forms to show inline validation errors.

The "Next" button is disabled, but I don't have information about *why* it's disabled. 

Either inline error messages after an invalid input is entered, or a tooltip over the "Submit" buttons which displays validation errors would help.

**Comment by Da-Colon** [comment]
@sethhrbek which screens are you referring to?

**Comment by sethhrbek** [comment]
@Da-Colon -- was referring to the DAO creation screen (I'll include screenshots next time).

However, this issue was related to the "no decimals" input not being validated, and since that has since been cleaned up im going to close this issue.
