### ISSUE TITLE
Bugfix: Create DAO failed transaction stays on Pending page

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#20]
When a user attempts to deploy a dao via a blockchain transaction, If a transaction fails or is rejected, the pending page gets stuck.

# Acceptance Criteria:

* When a transaction is created - the pending page should show.
* If a transaction is completed - should navigate to the specific dao page
* If a transaction fails - the pending page should go away and should be redirected back to the create dao page

**Comment by christopherdancy** [comment]
When a user attempts to deploy a dao via a blockchain transaction, If a transaction fails or is rejected, the pending page gets stuck.

Acceptance Criteria:
* When a transaction is created - the pending page should show.
* If a transaction is completed - should navigate to the specific dao page
* If a transaction fails - the pending page should go away and should be redirected back to the create dao page
