### ISSUE TITLE
Bugfix: wrong design on error message when searching for DAO with valid ethereum address

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#21]
# Acceptance Criteria

- The error message styling for when a valid Ethereum address is inputted that is not a valid Fractal DAO should match the error message styling for when an invalid Ethereum address is inputted.

**Comment by christopherdancy** [comment]
Acceptance Criteria
* When a

**Comment by christopherdancy** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/69045872/163035080-3d31571d-3bea-4154-9775-af41a79c92bd.png">
