### ISSUE TITLE
Web3 Modal bug

### ISSUE THREAD

**Issue by Da-Colon** [fractal-framework/fractal-interface#210]
![image](https://user-images.githubusercontent.com/38386583/167018449-2862c0f2-dee8-4101-8c55-b7a5416eb1bf.png)

![image](https://user-images.githubusercontent.com/38386583/167018465-4ff37fc2-ee54-440f-a3c4-28bff4a4bb60.png)

This may be a local issue. would like some others eyes on this
## Problem
Manually Disconnecting through metamask and dApp doesn't clear local storage data

## Things I've tried
- ensured I was disconnected from the dApp
- ensured that metamask account was also disconnected
- refresh local environment
- open new window

## Steps to reproduce. (still working on getting rid of it.)
I had at the time 2 different accounts connected. I disconnected one (in dApp first) then in metamask. hit connect wallet and the second account connected. Manually disconnected that account. The modal does pop up but when I click on wallet connect it goes to white screen (see #209, these may be related).

**Comment by Da-Colon** [comment]
@adamgall do you think this has anything to do with the changes to connect and disconnect moving inside web3 Provider

**Comment by adamgall** [comment]
@dannydecent plz see above

**Comment by dannydecent** [comment]
agreed. get rid of the "Disconnect" button in our menu

**Comment by Da-Colon** [comment]
@adamgall I can't reproduce on staging site. the bug may be local.

**Comment by Da-Colon** [comment]
I'm going to leave this issue open and throw it in the backlog. if we don't see this behavior repeated we close this. (reseting local cache fixed this for me locally and no longer and reproduce)
