### ISSUE TITLE
Allow User to choose proposal length on DAO deploy

### ISSUE THREAD

**Issue by Da-Colon** [fractal-framework/fractal-interface#242]
Opening an discussion on the lift it would take to allow a user to choose proposal length on DAO creation

**Comment by adamgall** [comment]
@Da-Colon i realize this might not seem important, but maybe the actual discussion could happen over in the `discussions` board of this repo?

**Comment by Da-Colon** [comment]
@adamgall I thought about it. but figured this could quickly turn into a task.

**Comment by Da-Colon** [comment]
but yeah you right for consistency? sake I'll move it over to discussions
