### ISSUE TITLE
Style global components

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#28]
The global components (header, footer) are currently implemented in wireframe-styling. This issue is to make the global components look like the designs on Figma.

# Acceptance criteria

* fully responsive -- components should "look good" on all screen sizes
* colors, spacings, borders, corners, etc should exist as reusable tailwind settings
  * individual components should have as little custom design as possible. keep it DRY

**Comment by christopherdancy** [comment]
Header Completed - However - designs for footer not included referencing footer issue/ #37
