### ISSUE TITLE
Shared "container" for proposal-level (and other?) components

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#82]
"Cast Vote" and "Results" components should definitely be sharing some container-level styling (so that the title and horizontal line are on the same latitude.

![165873907-b0f547f0-fd69-49cc-8d69-b84b9ccfab15](https://user-images.githubusercontent.com/706929/165967325-76ba3f4d-3047-4c4f-8347-436ba6f760fb.png)

_Originally posted by @adamgall in https://github.com/fractal-framework/fractal-interface/pull/80#discussion_r861777582_

**Comment by adamgall** [comment]
@Da-Colon would you say this has been handled with your latest slew of PRs?

**Comment by Da-Colon** [comment]
@adamgall yeah I would say this one is taken care of it
