### ISSUE TITLE
DAO Dashboard Action Items

### ISSUE THREAD

**Issue by adamgall** [fractal-framework/fractal-interface#86]
![Untitled](https://user-images.githubusercontent.com/706929/165977213-750afcda-41fc-41e7-88e6-1cd597cab618.png)

- Title: Proposals
- Voting Allocation should be a text button (should say "voting delegation" actually)
- Create a Proposal should be a primary button
- 1 pixel border below that

**Comment by dannydecent** [comment]
Change button names:
Voting Allocation > Delegate 
Create a New Proposal + > Create Proposal

**Comment by adamgall** [comment]
@Da-Colon would you say this has been handled with your latest slew of PRs?

**Comment by adamgall** [comment]
Related card: #87
